import { LuUser } from "react-icons/lu";
import Layout from "../../_layout";
import TableHeader from "../../components/TableHeader";
import { Link } from "react-router-dom";
import { CiFilter, CiSearch } from "react-icons/ci";

const DischargedPatient = () => {
  return (
    <Layout>
      <main className="px-4 pb-5 patient-page appointment-page">
        <div className="row mt-5">
          <div className="col-12">
            <div className="bg-white graph-card p-4 mb-4 ">
              <TableHeader heading={"IPD Discharged Patient"} />
            </div>
            <div className="col-12 col-lg-6 col-xl-4">
              <div className="mb-3 d-flex gap-3 search-box">
                <div className="position-relative">
                  <span className="input-group-text bg-white">
                    <CiSearch size={20} />
                  </span>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Search...."
                  />
                </div>
                <div className="filter-icon position-relative px-4">
                  <span className="">
                    <CiFilter size={20} />
                  </span>
                  <button className="btn shadow-none">Filter</button>
                </div>
              </div>
            </div>
            <div className="mt-4">
              <table className="table">
                <thead>
                  <tr>
                    <th scope="col">
                      <Link to="">Patient Name</Link>
                    </th>
                    <th scope="col">
                      <Link to="">Patient Id</Link>
                    </th>
                    <th scope="col">
                      <Link to="">Case Id</Link>
                    </th>
                    <th scope="col">
                      <Link to="">Gender</Link>
                    </th>
                    <th scope="col">
                      <Link to="">Generated By</Link>
                    </th>
                    <th scope="col">
                      <Link to="">Consultant Doctor</Link>
                    </th>
                    <th scope="col">
                      <Link to="">Admission Date</Link>
                    </th>
                    <th scope="col">
                      <Link to="">Discharged Date</Link>
                    </th>
                    <th scope="col">Tax ($)</th>
                    <th scope="col">Net Amount ($)</th>
                    <th scope="col">Total ($)</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>
                      <div className="d-flex align-items-center gap-3">
                        <div className="user-image d-flex align-items-center justify-content-center">
                          <LuUser />
                        </div>
                        <div className="user-info">
                          <Link>
                            <h5>Georgia Wareham (1155)</h5>
                          </Link>
                          <span>7896541230</span>
                        </div>
                      </div>
                    </td>
                    <td>1141</td>
                    <td>6914</td>
                    <td>Male</td>
                    <td>Super Admin (9001) </td>
                    <td>Amit Singh (9009) </td>
                    <td>10/30/2021 10:00 AM </td>
                    <td>11/03/2021 03:00 PM </td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                  </tr>

                  <tr>
                    <td>
                      <div className="d-flex align-items-center gap-3">
                        <div className="user-image d-flex align-items-center justify-content-center">
                          <LuUser />
                        </div>
                        <div className="user-info">
                          <Link>
                            <h5>Georgia Wareham (1155)</h5>
                          </Link>
                          <span>7896541230</span>
                        </div>
                      </div>
                    </td>
                    <td>1141</td>
                    <td>6914</td>
                    <td>Male</td>
                    <td>Super Admin (9001) </td>
                    <td>Amit Singh (9009) </td>
                    <td>10/30/2021 10:00 AM </td>
                    <td>11/03/2021 03:00 PM </td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                  </tr>

                  <tr>
                    <td>
                      <div className="d-flex align-items-center gap-3">
                        <div className="user-image d-flex align-items-center justify-content-center">
                          <LuUser />
                        </div>
                        <div className="user-info">
                          <Link>
                            <h5>Georgia Wareham (1155)</h5>
                          </Link>
                          <span>7896541230</span>
                        </div>
                      </div>
                    </td>
                    <td>1141</td>
                    <td>6914</td>
                    <td>Male</td>
                    <td>Super Admin (9001) </td>
                    <td>Amit Singh (9009) </td>
                    <td>10/30/2021 10:00 AM </td>
                    <td>11/03/2021 03:00 PM </td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                  </tr>

                  <tr>
                    <td>
                      <div className="d-flex align-items-center gap-3">
                        <div className="user-image d-flex align-items-center justify-content-center">
                          <LuUser />
                        </div>
                        <div className="user-info">
                          <Link>
                            <h5>Georgia Wareham (1155)</h5>
                          </Link>
                          <span>7896541230</span>
                        </div>
                      </div>
                    </td>
                    <td>1141</td>
                    <td>6914</td>
                    <td>Male</td>
                    <td>Super Admin (9001) </td>
                    <td>Amit Singh (9009) </td>
                    <td>10/30/2021 10:00 AM </td>
                    <td>11/03/2021 03:00 PM </td>
                    <td>0.00</td>
                    <td>0.00</td>
                    <td>0.00</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  );
};
export default DischargedPatient;
