import { LuUser } from "react-icons/lu"
import Layout from "../../_layout"
import TableHeader from "../../components/TableHeader"
import { Link } from "react-router-dom"
import CreateIdpModal from "../../components/CreateIdpModal"
import React, { useEffect, useRef, useState } from "react";
import { Modal } from "bootstrap";
import CreatePatient from "../../components/CreatePatient"

const IpdPatient = () => {

const [showCreateIdpModal, setShowCreateIdpModal] = useState(false);
  const CreateIdpModalRef = useRef(null);
  const CreateIdpModalInstance = useRef(null);

    useEffect(() => {
      if (CreateIdpModalInstance.current) {
        if (showCreateIdpModal) {
          CreateIdpModalInstance.current.show();
        } else {
          CreateIdpModalInstance.current.hide();
        }
      }
    }, [showCreateIdpModal]);
  
    // 1. Initialize the Bootstrap Modal instance when the component mounts
    useEffect(() => {
      
      if (CreateIdpModalRef.current) {
        CreateIdpModalInstance.current = new Modal(CreateIdpModalRef.current, {});
      }
  
    }, []);

    return(
       <Layout>
         <main className="px-4 pb-5 patient-page">
            <div className="row mt-5">
                <div className="col-12">
                    <div className="bg-white graph-card p-4">
                        <TableHeader 
                            heading={"IPD Patients"}
                            primaryBtnText={"Add Patient"}
                            primaryBtnClick={() => setShowCreateIdpModal(true)}
                            secontryBtnText={"Discharged Patient"}
                            secontryBtnClick={() => ("click secondry btn")}
                            
                        />
                    </div>
                    <div className="mt-4">
                        <table className="table">
                            <thead>
                                <tr>
                                <th scope="col">Patient Name</th>
                                <th scope="col">IPD No</th>
                                <th scope="col">Case ID</th>
                                <th scope="col">Gender</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Consultant Doctor</th>
                                <th scope="col">Bed</th>
                                <th scope="col">Is Antenatal</th>
                                <th scope="col">Previous Medical Issue</th>
                                <th scope="col">Credit Limit ($)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>90978567566</span>
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                        <Link to="#">IPDN112</Link>
                                    </td>
                                    <td>7402</td>
                                    <td>Female</td>
                                    <td>Super Admin (9001)	</td>
                                    <td>Reyan Jain (9011)	</td>
                                    <td>SF - 137-ICU-2nd Floor	</td>
                                    <td>No</td>
                                    <td>Na</td>
                                    <td>20000.00</td>
                                </tr>
                                
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>90978567566</span>
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                        <Link to="#">IPDN112</Link>
                                    </td>
                                    <td>7402</td>
                                    <td>Female</td>
                                    <td>Super Admin (9001)	</td>
                                    <td>Reyan Jain (9011)	</td>
                                    <td>SF - 137-ICU-2nd Floor	</td>
                                    <td>No</td>
                                    <td>Na</td>
                                    <td>20000.00</td>
                                </tr>
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>90978567566</span>
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                        <Link to="#">IPDN112</Link>
                                    </td>
                                    <td>7402</td>
                                    <td>Female</td>
                                    <td>Super Admin (9001)	</td>
                                    <td>Reyan Jain (9011)	</td>
                                    <td>SF - 137-ICU-2nd Floor	</td>
                                    <td>No</td>
                                    <td>Na</td>
                                    <td>20000.00</td>
                                </tr>
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>90978567566</span>
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                        <Link to="#">IPDN112</Link>
                                    </td>
                                    <td>7402</td>
                                    <td>Female</td>
                                    <td>Super Admin (9001)	</td>
                                    <td>Reyan Jain (9011)	</td>
                                    <td>SF - 137-ICU-2nd Floor	</td>
                                    <td>No</td>
                                    <td>Na</td>
                                    <td>20000.00</td>
                                </tr>
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>90978567566</span>
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                        <Link to="#">IPDN112</Link>
                                    </td>
                                    <td>7402</td>
                                    <td>Female</td>
                                    <td>Super Admin (9001)	</td>
                                    <td>Reyan Jain (9011)	</td>
                                    <td>SF - 137-ICU-2nd Floor	</td>
                                    <td>No</td>
                                    <td>Na</td>
                                    <td>20000.00</td>
                                </tr>
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>90978567566</span>
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                        <Link to="#">IPDN112</Link>
                                    </td>
                                    <td>7402</td>
                                    <td>Female</td>
                                    <td>Super Admin (9001)	</td>
                                    <td>Reyan Jain (9011)	</td>
                                    <td>SF - 137-ICU-2nd Floor	</td>
                                    <td>No</td>
                                    <td>Na</td>
                                    <td>20000.00</td>
                                </tr>
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>90978567566</span>
                                            </div>
                                        </div>
                                    </td>
                                     <td>
                                        <Link to="#">IPDN112</Link>
                                    </td>
                                    <td>7402</td>
                                    <td>Female</td>
                                    <td>Super Admin (9001)	</td>
                                    <td>Reyan Jain (9011)	</td>
                                    <td>SF - 137-ICU-2nd Floor	</td>
                                    <td>No</td>
                                    <td>Na</td>
                                    <td>20000.00</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div
            className="modal fade create-appointment-modal"
            ref={CreateIdpModalRef}
            onHide={() => setShowCreateIdpModal(false)}
            data-bs-backdrop="static"
            data-bs-keyboard="false"
            tabIndex="-1"
          >
            <div className="modal-dialog modal-xl">
              <CreateIdpModal 
                handleCloseModal={() => setShowCreateIdpModal(false)}
              />
            </div>
          </div>
         </main>
       </Layout>
    )
}

export default IpdPatient