import { LuUser } from "react-icons/lu"
import Layout from "../../_layout"
import TableHeader from "../../components/TableHeader"

const IpdPatient = () => {
    return(
       <Layout>
         <main className="px-4 pb-5 patient-page">
            <div className="row mt-5">
                <div className="col-12">
                    <div className="bg-white graph-card p-4">
                        <TableHeader 
                            heading={"IPD Patients"}
                            primaryBtnText={"Add Patient"}
                            primaryBtnClick={() => setShowCreatePatientModal(true)}
                            secontryBtnText={"Discharged Patient"}
                            secontryBtnClick={() => console.log("click secondry btn")}
                        />
                    </div>
                    <div className="mt-4">
                        <table className="table">
                            <thead>
                                <tr>
                                <th scope="col">Name</th>
                                <th scope="col">IPD No</th>
                                <th scope="col">Case ID</th>
                                <th scope="col">Gender</th>
                                <th scope="col">Phone</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Consultant Doctor</th>
                                <th scope="col">Bed</th>
                                <th scope="col">Is Antenatal</th>
                                <th scope="col">Previous Medical Issue</th>
                                <th scope="col">Credit Limit ($)</th>

                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <div className="d-flex align-items-center gap-3">
                                            <div className="user-image d-flex align-items-center justify-content-center">
                                                <LuUser />
                                            </div>
                                            <div className="user-info">
                                                <h5>Georgia Wareham (1155)</h5>
                                            <span>5869325412</span>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                <tr></tr>
                                <tr></tr>
                                <tr></tr>
                                <tr></tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
         </main>
       </Layout>
    )
}

export default IpdPatient